# Generated by Django 5.2.7 on 2025-10-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientousuario',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
