# Generated by Django 5.2.7 on 2025-10-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_movimientousuario_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientousuario',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='movimientousuario',
            name='metodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientousuario',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movimientousuario',
            name='accion',
            field=models.CharField(max_length=255),
        ),
    ]
