# Generated by Django 5.2.7 on 2025-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_movimientousuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientousuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='movimientousuario',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='movimientousuario',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='movimientousuario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientousuario',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación'), ('IMPORTAR', 'Importación masiva'), ('ELIMINAR_TODOS', 'Eliminación total')], max_length=50),
        ),
    ]
