# Generated by Django 5.2.7 on 2025-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_movimientousuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientousuario',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación'), ('IMPORTAR', 'Importación masiva'), ('ELIMINAR_TODOS', 'Eliminación total')], max_length=20),
        ),
    ]
