# Generated by Django 5.2.7 on 2025-10-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('cod_ean', models.CharField(max_length=50)),
                ('cod_dun', models.CharField(max_length=50)),
                ('cod_sistema', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=350)),
                ('unidad', models.CharField(max_length=20)),
                ('pack', models.IntegerField()),
                ('factorx', models.FloatField()),
                ('cajas', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('stock_fisico', models.IntegerField()),
                ('observacion', models.TextField(blank=True, max_length=350, null=True)),
                ('fecha_inv', models.DateField()),
                ('encargado', models.CharField(max_length=100)),
                ('fecha_imp', models.DateField(blank=True, null=True)),
                ('numero_contenedor', models.CharField(blank=True, max_length=100, null=True)),
                ('Data_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
    ]
