# Generated by Django 5.2.7 on 2025-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_cajas_alter_producto_cod_dun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_venc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
