# Generated by Django 5.2.7 on 2025-10-22 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_data_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_imp',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_inv',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
